version: '3.7'

services:
    baymax:
        build: .
        container_name: baymax
        restart: always
        ports:
            - 5000:5000
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: baymax
        ports:
            - 27017:27017
        volumes: 
            - mongodb:/data/db

volumes:
    mongodb: